version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    registries:
      - npm-github
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
      babel:
        patterns:
          - "@babel*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      github:
        patterns:
          - "*"
