name: Build

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true
        inputs:
            package-name:
                required: true
                type: string
            upload-artifact:
                required: false
                type: boolean
                default: false
            artifact-path:
                required: false
                type: string
                default: ./build

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Installere moduler
              run: yarn install --prefer-offline --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre bygg
              run: lerna run build --scope ${{inputs.package-name}}
            - uses: actions/upload-artifact@v3
              if: ${{inputs.upload-artifact}}
              with:
                  name: build
                  path: ${{ inputs.artifact-path }}
