name: Cypress test

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true
        inputs:
            package-name:
                required: true
                type: string
            project:
                required: true
                type: string

jobs:
    cypress-test:
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Cypress run
              uses: cypress-io/github-action@v5
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  project: ${{inputs.project}}
                  build: yarn build
                  start: lerna run dev --scope ${{inputs.package-name}}
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
