name: Deploy preprod Medisinsk vilkår
on: [workflow_dispatch]
env:
    IMAGE_BASE: ghcr.io/${{ github.repository }}/medisinsk-vilkar-frontend
    package-name: medisinsk-vilkar-frontend

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
            upload-artifact: true
            artifact-path: ./packages/medisinsk-vilkår/build/
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    cypress-test:
        uses: ./.github/workflows/cypress-test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
            project: ./packages/medisinsk-vilkår
    deploy-docker-image:
        name: Deploy Docker image
        runs-on: ubuntu-latest
        needs: [lint, build, test, cypress-test]
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - uses: actions/download-artifact@v3
              with:
                  name: build
                  path: ./build
            - name: Sette versjon
              working-directory: ./packages/medisinsk-vilkår
              run: |
                  echo "MAJOR_VERSION=$(npm run majorVersion --silent)" >> $GITHUB_ENV
            - name: Sette tag
              run: |
                  echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            - name: Sette miljøvariabler
              run: |
                  echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
                  echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
                  echo "CSS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/styles.css | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
                  echo "JS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/app.js | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
            # - name: Bygg og laste opp docker-image
            #   run: |
            #       docker build --tag ${IMAGE} --tag ${LATEST} .
            #       echo "$GITHUB_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
            #       docker push ${IMAGE}
            #       docker push ${LATEST}
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Deploy til dev-fss
            #   uses: nais/deploy/actions/deploy@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            #       CLUSTER: dev-fss
            #       RESOURCE: ./packages/medisinsk-vilkår/nais/naiserator.yml
            #       VARS: ./packages/medisinsk-vilkår/nais/dev-fss.json
