name: Deploy all microfrontends to prod
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ prod ]
        application: [
          psb-etablert-tilsyn-frontend,
          psb-inntektsmelding-frontend,
          medisinsk-vilkar-frontend,
          psb-om-barnet-frontend,
          omsorgen-for-frontend,
          omsorgsdager-frontend,
          psb-uttak-frontend
        ]
    steps:
      - name: Deploy ${{ matrix.application }} to ${{ matrix.environment }}
        uses: ./.github/workflows/deploy-microfrontend.yml
        with:
          environment: ${{ matrix.environment }}
          application: ${{ matrix.application }}