name: Deploy preprod Medisinsk vilkår
on: [workflow_dispatch]
env:
    IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/medisinsk-vilkar-frontend
    package-name: medisinsk-vilkar-frontend

jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    cypress-test:
        uses: ./.github/workflows/cypress-test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
            project: ./packages/medisinsk-vilkår
    deploy-docker-image:
        name: Deploy Docker image
        runs-on: ubuntu-latest
        needs: [lint, build, test, cypress-test]
        steps:
            - name: Sette versjon
              run: |
                  echo "MAJOR_VERSION=$(npm run majorVersion --silent)" >> $GITHUB_ENV
            - name: Sette tag
              run: |
                  echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            - name: Sette miljøvariabler
              run: |
                  echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
                  echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
                  echo "CSS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/styles.css | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
                  echo "JS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/app.js | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
