name: Deploy all microfrontends prod

on:
  push:
    branches:
      - main

jobs:
  dispatch_workflows:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Dispatch Deploy Omsorgsdager workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-omsorgsdager
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Uttak workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-uttak
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Etablert Tilsyn workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-etablert-tilsyn
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Inntektsmelding workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-inntektsmelding
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Medisinsk Vilkår workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-medisinsk-vilkar
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Om Barnet workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-om-barnet
          client-payload: '{"ref": "main", "environment": "Prod"}'

      - name: Dispatch Deploy Omsorgen For workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deploy-omsorgen-for
          client-payload: '{"ref": "main", "environment": "Prod"}'
