name: Deploy preprod Medisinsk vilkår
on: [workflow_dispatch]
env:
    IMAGE_BASE: ghcr.io/${{ github.repository }}/medisinsk-vilkar-frontend
    package-name: medisinsk-vilkar-frontend

jobs:
    deploy-docker-image:
        name: Deploy Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Installere dependencies
              run: yarn install --prefer-offline --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre linter
              run: lerna run lint --scope ${{env.package-name}}
            - name: Valider typescript
              run: lerna run ts-check --scope ${{env.package-name}}
            - name: Kjøre enhetstester
              run: lerna run test --scope ${{env.package-name}}
            - name: Kjør E2E-tester
              uses: cypress-io/github-action@v5
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  install: false
                  project: ./packages/medisinsk-vilkår
                  build: lerna run build --scope '{@navikt/k9-array-utils,@navikt/k9-bem-utils,@navikt/k9-date-utils,@navikt/k9-form-utils,@navikt/k9-http-utils,@navikt/k9-period-utils}'
                  start: lerna run dev --scope medisinsk-vilkar-frontend
                  wait-on: 'http://localhost:8081'
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  working-directory: ./packages/medisinsk-vilkår
            - name: Kjøre bygg
              run: lerna run build --scope ${{env.package-name}}
            - name: Sette versjon
              working-directory: ./packages/medisinsk-vilkår
              run: |
                  echo "MAJOR_VERSION=$(npm run majorVersion --silent)" >> $GITHUB_ENV
            - name: Sette tag
              run: |
                  echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
            - name: Sette miljøvariabler
              run: |
                  echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
                  echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
                  echo "CSS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/styles.css | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
                  echo "JS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/app.js | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
            # - name: Bygg og laste opp docker-image
            #   run: |
            #       docker build --tag ${IMAGE} --tag ${LATEST} .
            #       echo "$GITHUB_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
            #       docker push ${IMAGE}
            #       docker push ${LATEST}
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # - name: Deploy til dev-fss
            #   uses: nais/deploy/actions/deploy@v1
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #       APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            #       CLUSTER: dev-fss
            #       RESOURCE: ./packages/medisinsk-vilkår/nais/naiserator.yml
            #       VARS: ./packages/medisinsk-vilkår/nais/dev-fss.json
