name: Test

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true
        inputs:
            package-name:
                required: true
                type: string
            run-cypress:
                required: false
                type: boolean
                default: false

jobs:
    enhetstester:
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Installere moduler
              run: yarn install --prefer-offline --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre enhetstester
              run: lerna run test --scope ${{inputs.package-name}}
            - name: Cypress run
              uses: cypress-io/github-action@v5
              if: ${{inputs.run-cypress}}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  project: ${{inputs.project}}
                  build: lerna run build --scope '{@navikt/k9-array-utils,@navikt/k9-bem-utils,@navikt/k9-date-utils,@navikt/k9-form-utils,@navikt/k9-http-utils,@navikt/k9-period-utils}'
                  start: lerna run dev --scope ${{inputs.package-name}}
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: ${{inputs.run-cypress}} && failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
