name: Test

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true
        inputs:
            package-name:
                required: true
                type: string
            run-cypress:
                required: false
                type: boolean
                default: false

jobs:
    enhetstester:
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Sette opp Node
              uses: actions/setup-node@v3
                  
            - name: Installere dependencies
              run: yarn install --immutable
            - name: Kjøre enhetstester
              run: yarn lerna run test --scope ${{inputs.package-name}}
            - name: Cypress run
              uses: cypress-io/github-action@v6
              if: ${{inputs.run-cypress}}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  project: ${{inputs.project}}
                  build: yarn build-frontend-modules
                  start: yarn lerna run dev --scope ${{inputs.package-name}}
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: ${{inputs.run-cypress}} && failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
