name: Test

on:
    workflow_call:
        secrets:
            READER_TOKEN:
                required: true
        inputs:
            package-name:
                required: true
                type: string
            run-cypress:
                required: false
                type: boolean
                default: false

jobs:
    enhetstester:
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 7
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'pnpm'
            - name: Installere moduler
              run: pnpm install
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre enhetstester
              run: lerna run test --scope ${{inputs.package-name}}
            - name: Cypress run
              uses: cypress-io/github-action@v5
              if: ${{inputs.run-cypress}}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  project: ${{inputs.project}}
                  build: lerna run build --scope '{@navikt/k9-fe-array-utils,@navikt/k9-fe-bem-utils,@navikt/k9-fe-date-utils,@navikt/k9-fe-form-utils,@navikt/k9-fe-http-utils,@navikt/k9-fe-period-utils}'
                  start: lerna run dev --scope ${{inputs.package-name}}
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: ${{inputs.run-cypress}} && failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
