name: Validere pull request Omsorgen for
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/omsorgen-for/**/*'
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: omsorgen-for-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: omsorgen-for-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: omsorgen-for-frontend
