name: Validere pull request Etablert tilsyn
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/etablert-tilsyn/**/*'
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: psb-etablert-tilsyn-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: psb-etablert-tilsyn-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: psb-etablert-tilsyn-frontend
