name: Validere pull request Om barnet
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/om-barnet/**/*'
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: psb-om-barnet-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: psb-om-barnet-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: psb-om-barnet-frontend
