name: Validere pull request Medisinsk vilkår
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/medisinsk-vilkår/**/*'
env:
    package-name: medisinsk-vilkar-frontend
jobs:
    valid-pull-request:
        name: Validere pull request
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  cache: 'yarn'
            - name: Installere dependencies
              run: yarn install --immutable
            - name: Bygg k9-frontend-modules
              run: lerna run build --scope '{@navikt/k9-fe-array-utils,@navikt/k9-fe-bem-utils,@navikt/k9-fe-date-utils,@navikt/k9-fe-form-utils,@navikt/k9-fe-http-utils,@navikt/k9-fe-period-utils}'
            - name: Kjøre linter
              run: lerna run lint --scope ${{env.package-name}}
            - name: Valider typescript
              run: lerna run ts-check --scope ${{env.package-name}}
            - name: Kjøre enhetstester
              run: lerna run test --scope ${{env.package-name}}
            - name: Kjør E2E-tester
              uses: cypress-io/github-action@v5
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  install: false
                  project: ./packages/medisinsk-vilkår
                  start: lerna run dev --scope medisinsk-vilkar-frontend
                  wait-on: 'http://localhost:8081'
                  wait-on-timeout: 60
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
            - name: Kjøre bygg
              run: lerna run build --scope ${{env.package-name}}
