name: Validere pull request Etablert tilsyn
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/psb-etablert-tilsyn-frontend/**/*'
env:
    package-name: psb-etablert-tilsyn-frontend
jobs:
    valid-pull-request:
        name: Validere pull request
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v4
            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Sette opp Node
              uses: actions/setup-node@v3
                  
            - name: Get cypress cache directory path
              id: cypress-cache-dir
              run: echo "CYPRESS_BIN_PATH=$(npx cypress cache path)" >> $GITHUB_OUTPUT
            - uses: actions/cache@v3
              id: cypress-cache
              with:
                  path: |
                      ${{ steps.cypress-cache-dir.outputs.CYPRESS_BIN_PATH }}
                  key: ${{ runner.os }}-yarn-cypress-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-cypress-
            - name: Installere dependencies
              run: yarn install --immutable
            - name: Bygg k9-frontend-modules
              run: yarn build-frontend-modules
            - name: Kjøre linter
              run: yarn lerna run lint --scope ${{env.package-name}}
            - name: Valider typescript
              run: yarn lerna run ts-check --scope ${{env.package-name}}
            - name: Kjøre enhetstester
              run: yarn lerna run test --scope ${{env.package-name}}
            - name: Kjør E2E-tester
              uses: cypress-io/github-action@v6
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  install: false
                  project: ./packages/etablert-tilsyn
                  start: lerna run dev --scope psb-etablert-tilsyn-frontend
                  wait-on: 'http://localhost:8484'
                  wait-on-timeout: 60
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: packages/**/cypress/screenshots
            - name: Kjøre bygg
              run: yarn lerna run build --scope ${{env.package-name}}
