name: Validere pull request Medisinsk vilkår
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/medisinsk-vilkår/**/*'
env:
    package-name: medisinsk-vilkar-frontend
jobs:
    valid-pull-request:
        name: Validere pull request
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./packages/medisinsk-vilkår
        steps:
            - name: Hente kode
              uses: actions/checkout@v3
            - name: Sette opp Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  registry-url: https://npm.pkg.github.com/
                  scope: '@navikt'
                  cache: 'yarn'
            - name: Installere dependencies
              run: yarn install --prefer-offline --frozen-lockfile
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Kjøre linter
              run: lerna run lint --scope ${{env.package-name}}
            - name: Valider typescript
              run: lerna run ts-check --scope ${{env.package-name}}
            - name: Kjøre enhetstester
              run: lerna run test --scope ${{env.package-name}}
            - name: Kjør E2E-tester
              uses: cypress-io/github-action@v5
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
              with:
                  project: ./packages/medisinsk-vilkår
                  build: lerna run build --scope '{@navikt/k9-array-utils,@navikt/k9-bem-utils,@navikt/k9-date-utils,@navikt/k9-form-utils,@navikt/k9-http-utils,@navikt/k9-period-utils}'
                  start: lerna run dev --scope ${{inputs.package-name}}
                  wait-on: 'http://localhost:8081'
                  wait-on-timeout: 60
                  headless: true
            - name: Laster opp screenshots dersom Cypress-testene feiler
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  working-directory: ./packages/medisinsk-vilkår
            - name: Kjøre bygg
              run: lerna run build --scope ${{env.package-name}}
