name: Validere pull request Medisinsk vilkår
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/medisinsk-vilkår/**/*'
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
    cypress-test:
        uses: ./.github/workflows/cypress-test.yml
        secrets: inherit
        with:
            package-name: medisinsk-vilkar-frontend
            project: ./packages/medisinsk-vilkår
