name: Validere pull request Om barnet
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/om-barnet/**/*'
            - 'yarn.lock'
env:
    package-name: '@navikt/k9-fe-om-barnet'
jobs:
    valid-pull-request:
        name: Validere pull request
        runs-on: ubuntu-latest
        steps:
            - name: Hente kode
              uses: actions/checkout@v4
            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.navikt.npmRegistryServer "https://npm.pkg.github.com"
                  yarn config set npmScopes.navikt.npmAlwaysAuth true
                  yarn config set npmScopes.navikt.npmAuthToken $NPM_AUTH_TOKEN
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
            - name: Sette opp Node
              uses: actions/setup-node@v4
              with:
                  cache: 'yarn'
            - name: Installere dependencies
              run: yarn install --immutable
            - name: Bygg k9-frontend-modules
              run: yarn build-frontend-modules
            - name: Kjøre linter
              run: yarn lerna run lint --scope ${{env.package-name}}
            - name: Valider typescript
              run: yarn lerna run ts-check --scope ${{env.package-name}}
            - name: Kjøre enhetstester
              run: yarn lerna run test --scope ${{env.package-name}}
            - name: Kjøre bygg
              run: yarn lerna run build --scope ${{env.package-name}}
