name: Validere pull request Inntektsmelding
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/inntektsmelding/**/*'
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        secrets: inherit
        with:
            package-name: psb-inntektsmelding-frontend
    build:
        uses: ./.github/workflows/build.yml
        secrets: inherit
        with:
            package-name: psb-inntektsmelding-frontend
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
        with:
            package-name: psb-inntektsmelding-frontend
